### ISSUE TITLE
train end error.

### ISSUE THREAD

**Issue by simplew2011** [raadon96/MVTec-Anomaly-Detection#55]
Found 223 images belonging to 1 classes.
Found 24 images belonging to 1 classes.
INFO:autoencoder.autoencoder:initiating learning rate finder to determine best learning rate.
simulating training for different learning rates... this may take a few moments...
Epoch 1/10
13/13 [==============================] - 152s 12s/step - loss: 0.6025 - mssim: 0.3975
Epoch 2/10
13/13 [==============================] - 152s 12s/step - loss: 0.5974 - mssim: 0.4026
Epoch 3/10
13/13 [==============================] - 156s 12s/step - loss: 0.5921 - mssim: 0.4079
Epoch 4/10
13/13 [==============================] - 155s 12s/step - loss: 0.5702 - mssim: 0.4298
Epoch 5/10
13/13 [==============================] - 156s 12s/step - loss: nan - mssim: nan
Epoch 6/10
13/13 [==============================] - 155s 12s/step - loss: nan - mssim: nan
Epoch 7/10
13/13 [==============================] - 148s 11s/step - loss: nan - mssim: nan
Epoch 8/10
13/13 [==============================] - 146s 11s/step - loss: nan - mssim: nan
Epoch 9/10
13/13 [==============================] - 144s 11s/step - loss: nan - mssim: nan
Epoch 10/10
13/13 [==============================] - 143s 11s/step - loss: nan - mssim: nan

done.
Visually inspect loss plot and select learning rate associated with falling loss
INFO:autoencoder.autoencoder:lr with minimum loss divided by 10: 8.09E-04
INFO:autoencoder.autoencoder:lr with minimum numerical gradient: 8.38E-05
C:\Users\Administrator\Desktop\MVTec-Anomaly-Detection-master\autoencoder\autoencoder.py:231: RuntimeWarning: invalid value encountered in less
  self.lr_opt_i = np.argwhere(segment < optimal_loss)[0][0]
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main(args)
  File "train.py", line 81, in main
    autoencoder.find_lr_opt(train_generator, validation_generator)
  File "C:\Users\Administrator\Desktop\MVTec-Anomaly-Detection-master\autoencoder\autoencoder.py", line 194, in find_lr_opt
    self.custom_lr_estimate()
  File "C:\Users\Administrator\Desktop\MVTec-Anomaly-Detection-master\autoencoder\autoencoder.py", line 231, in custom_lr_estimate
    self.lr_opt_i = np.argwhere(segment < optimal_loss)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by init-22** [comment]
@simplew2011 did you solve this?

**Comment by pandego** [comment]
I was having the same issue, only when using custom datasets... it worked fine with MVTEC datasets.
Solved it by increasing the size of the dataset (number of images).
